version: '3.3'

services:
  db:
    image: postgres:latest
    container_name: db
    restart: always
    environment:
      POSTGRES_USER:
      POSTGRES_PASSWORD:
      POSTGRES_DB: store
      TZ: Europe/Moscow
    volumes:
      - postgres_data:/var/lib/postgresql/data/

  api:
    build:
      context: .
      dockerfile: src/Dockerfile
    container_name: api
    working_dir: /usr/src/app/src
    restart: on-failure
    env_file:
      - ./src/core/.env
    depends_on:
      - db
    command: uvicorn main:app --host 0.0.0.0 --port 8000

  nginx:
    build: ./nginx/dev
    restart: on-failure
    container_name: nginx
    ports:
      - "8081:8081"
      - "8082:8082"
    depends_on:
      - api

volumes:
  postgres_data: