version: '3.3'

services:
  db:
    image: postgres:15.2
    container_name: db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: store
      TZ: Europe/Moscow
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    ports:
      - "5432:5432"

  api:
    build:
      context: .
      dockerfile: src/Dockerfile
    container_name: api
    working_dir: /usr/src/app/src
    restart: on-failure
    env_file:
      - ./src/core/.env
    ports:
      - "8000:8000"
    depends_on:
      - db
    command: uvicorn main:app --host 0.0.0.0 --port 8000

volumes:
  postgres_data: