"""Price and Price type models

Revision ID: 02db7bb10d85
Revises: dcd42f148948
Create Date: 2024-08-20 21:01:10.709449

"""

from alembic import op
import sqlalchemy as sa

import db

# revision identifiers, used by Alembic.
revision: str | None = "02db7bb10d85"
down_revision: str | None = "dcd42f148948"
branch_labels: str | None = None
depends_on: str | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "price_types",
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("guid", db.models.mixins.GUID(), nullable=False),
        sa.PrimaryKeyConstraint("guid", name=op.f("price_types_pkey")),
    )
    op.create_table(
        "prices",
        sa.Column("good_guid", sa.String(length=255), nullable=False),
        sa.Column("specification_guid", sa.String(length=255), nullable=False),
        sa.Column("price_type_guid", sa.String(length=255), nullable=False),
        sa.Column("value", sa.Float(), nullable=False),
        sa.ForeignKeyConstraint(
            ["good_guid"], ["goods.guid"], name=op.f("prices_good_guid_fkey")
        ),
        sa.ForeignKeyConstraint(
            ["price_type_guid"],
            ["price_types.guid"],
            name=op.f("prices_price_type_guid_fkey"),
        ),
        sa.ForeignKeyConstraint(
            ["specification_guid"],
            ["specifications.guid"],
            name=op.f("prices_specification_guid_fkey"),
        ),
        sa.PrimaryKeyConstraint(
            "good_guid",
            "specification_guid",
            "price_type_guid",
            name="good_spec_type_constraint",
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("prices")
    op.drop_table("price_types")
    # ### end Alembic commands ###
