"""Add ShoppingCart Model

Revision ID: 6cc31e77492d
Revises: 02db7bb10d85
Create Date: 2024-11-17 13:47:43.380989

"""

from alembic import op
import sqlalchemy as sa

import db

# revision identifiers, used by Alembic.
revision: str | None = "6cc31e77492d"
down_revision: str | None = "02db7bb10d85"
branch_labels: str | None = None
depends_on: str | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "carts",
        sa.Column("outlet_guid", sa.String(length=255), nullable=False),
        sa.PrimaryKeyConstraint("outlet_guid", name=op.f("carts_pkey")),
    )
    op.create_table(
        "goods_carts",
        sa.Column("good_guid", sa.String(length=255), nullable=True),
        sa.Column("specification_guid", db.models.mixins.GUID(), nullable=True),
        sa.Column("cart_guid", sa.String(length=255), nullable=False),
        sa.Column("quantity", sa.Integer(), nullable=False),
        sa.Column("price", sa.Float(), nullable=False),
        sa.ForeignKeyConstraint(
            ["cart_guid"],
            ["carts.outlet_guid"],
            name=op.f("goods_carts_cart_guid_fkey"),
        ),
        sa.ForeignKeyConstraint(
            ["good_guid"], ["goods.guid"], name=op.f("goods_carts_good_guid_fkey")
        ),
        sa.ForeignKeyConstraint(
            ["specification_guid"],
            ["specifications.guid"],
            name=op.f("goods_carts_specification_guid_fkey"),
        ),
        sa.PrimaryKeyConstraint("cart_guid", name=op.f("goods_carts_pkey")),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("goods_carts")
    op.drop_table("carts")
    # ### end Alembic commands ###
