"""Storage model

Revision ID: dcd42f148948
Revises: 3d56f697d37c
Create Date: 2024-07-28 15:00:51.633457

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str | None = "dcd42f148948"
down_revision: str | None = "3d56f697d37c"
branch_labels: str | None = None
depends_on: str | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "good_storages",
        sa.Column("in_stock", sa.Integer(), nullable=False),
        sa.Column("good_guid", sa.String(length=255), nullable=False),
        sa.Column("specification_guid", sa.String(length=255), nullable=False),
        sa.ForeignKeyConstraint(
            ["good_guid"], ["goods.guid"], name=op.f("good_storages_good_guid_fkey")
        ),
        sa.ForeignKeyConstraint(
            ["specification_guid"],
            ["specifications.guid"],
            name=op.f("good_storages_specification_guid_fkey"),
        ),
        sa.PrimaryKeyConstraint(
            "good_guid", "specification_guid", name="good_spec_constraint"
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("good_storages")
    # ### end Alembic commands ###
