"""Add ShoppingCart Model

Revision ID: fc9b93ca6485
Revises: 02db7bb10d85
Create Date: 2024-11-17 16:44:10.403312

"""
from alembic import op
import sqlalchemy as sa

import db

# revision identifiers, used by Alembic.
revision: str | None = 'fc9b93ca6485'
down_revision: str | None = '02db7bb10d85'
branch_labels: str | None = None
depends_on: str | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('carts',
    sa.Column('outlet_guid', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('outlet_guid', name=op.f('carts_pkey'))
    )
    op.create_table('goods_carts',
    sa.Column('good_guid', sa.String(length=255), nullable=False),
    sa.Column('specification_guid', db.models.mixins.GUID(), nullable=False),
    sa.Column('outlet_guid', sa.String(length=255), nullable=False),
    sa.Column('price_type_guid', db.models.mixins.GUID(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['good_guid'], ['goods.guid'], name=op.f('goods_carts_good_guid_fkey')),
    sa.ForeignKeyConstraint(['outlet_guid'], ['carts.outlet_guid'], name=op.f('goods_carts_outlet_guid_fkey')),
    sa.ForeignKeyConstraint(['price_type_guid'], ['price_types.guid'], name=op.f('goods_carts_price_type_guid_fkey')),
    sa.ForeignKeyConstraint(['specification_guid'], ['specifications.guid'], name=op.f('goods_carts_specification_guid_fkey'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('goods_carts')
    op.drop_table('carts')
    # ### end Alembic commands ###
